---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment-two
  labels:
    app: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 1
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-application
        image: gcr.io/cicd-gke-388407/springboot-app:latest
        ports:
        - containerPort: 8080    
---
apiVersion: v1
kind: Service
metadata:
 name: my-service-two
 labels:
   app: my-app
spec:
  selector:
    app: my-app
  type: NodePort 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30083
  
