---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment-one
  labels:
    app: my-app-one
spec:
  selector:
    matchLabels:
      app: my-app-one
  replicas: 1
  template:
    metadata:
      labels:
        app: my-app-one
    spec:
      containers:
      - name: my-application
        image: gcr.io/cicd-gke-388407/springboot-app:latest
        ports:
        - containerPort: 8082    
---
apiVersion: v1
kind: Service
metadata:
 name: my-service-one
 labels:
   app: my-app-one
spec:
  selector:
    app: my-app-one
  ports:
    - port: 8082
      targetPort: 8082
  type: LoadBalancer
